# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/suncio/Desktop/Genetic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/suncio/Desktop/Genetic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suncio/Desktop/Genetic/CMakeFiles /home/suncio/Desktop/Genetic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suncio/Desktop/Genetic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Genetic

# Build rule for target.
Genetic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Genetic
.PHONY : Genetic

# fast build rule for target.
Genetic/fast:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/build
.PHONY : Genetic/fast

Src/CliqueFinder.o: Src/CliqueFinder.cpp.o

.PHONY : Src/CliqueFinder.o

# target to build an object file
Src/CliqueFinder.cpp.o:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/CliqueFinder.cpp.o
.PHONY : Src/CliqueFinder.cpp.o

Src/CliqueFinder.i: Src/CliqueFinder.cpp.i

.PHONY : Src/CliqueFinder.i

# target to preprocess a source file
Src/CliqueFinder.cpp.i:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/CliqueFinder.cpp.i
.PHONY : Src/CliqueFinder.cpp.i

Src/CliqueFinder.s: Src/CliqueFinder.cpp.s

.PHONY : Src/CliqueFinder.s

# target to generate assembly for a file
Src/CliqueFinder.cpp.s:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/CliqueFinder.cpp.s
.PHONY : Src/CliqueFinder.cpp.s

Src/Graph.o: Src/Graph.cpp.o

.PHONY : Src/Graph.o

# target to build an object file
Src/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Graph.cpp.o
.PHONY : Src/Graph.cpp.o

Src/Graph.i: Src/Graph.cpp.i

.PHONY : Src/Graph.i

# target to preprocess a source file
Src/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Graph.cpp.i
.PHONY : Src/Graph.cpp.i

Src/Graph.s: Src/Graph.cpp.s

.PHONY : Src/Graph.s

# target to generate assembly for a file
Src/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Graph.cpp.s
.PHONY : Src/Graph.cpp.s

Src/Organism.o: Src/Organism.cpp.o

.PHONY : Src/Organism.o

# target to build an object file
Src/Organism.cpp.o:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Organism.cpp.o
.PHONY : Src/Organism.cpp.o

Src/Organism.i: Src/Organism.cpp.i

.PHONY : Src/Organism.i

# target to preprocess a source file
Src/Organism.cpp.i:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Organism.cpp.i
.PHONY : Src/Organism.cpp.i

Src/Organism.s: Src/Organism.cpp.s

.PHONY : Src/Organism.s

# target to generate assembly for a file
Src/Organism.cpp.s:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Organism.cpp.s
.PHONY : Src/Organism.cpp.s

Src/Vertex.o: Src/Vertex.cpp.o

.PHONY : Src/Vertex.o

# target to build an object file
Src/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Vertex.cpp.o
.PHONY : Src/Vertex.cpp.o

Src/Vertex.i: Src/Vertex.cpp.i

.PHONY : Src/Vertex.i

# target to preprocess a source file
Src/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Vertex.cpp.i
.PHONY : Src/Vertex.cpp.i

Src/Vertex.s: Src/Vertex.cpp.s

.PHONY : Src/Vertex.s

# target to generate assembly for a file
Src/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/Vertex.cpp.s
.PHONY : Src/Vertex.cpp.s

Src/main.o: Src/main.cpp.o

.PHONY : Src/main.o

# target to build an object file
Src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/main.cpp.o
.PHONY : Src/main.cpp.o

Src/main.i: Src/main.cpp.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Genetic.dir/build.make CMakeFiles/Genetic.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Genetic"
	@echo "... edit_cache"
	@echo "... Src/CliqueFinder.o"
	@echo "... Src/CliqueFinder.i"
	@echo "... Src/CliqueFinder.s"
	@echo "... Src/Graph.o"
	@echo "... Src/Graph.i"
	@echo "... Src/Graph.s"
	@echo "... Src/Organism.o"
	@echo "... Src/Organism.i"
	@echo "... Src/Organism.s"
	@echo "... Src/Vertex.o"
	@echo "... Src/Vertex.i"
	@echo "... Src/Vertex.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

